update develop to use -SNAPSHOT versions; add workflow to publish snapshots to GitHub packages

diff --git a/.github/workflows/release-common.yml b/.github/workflows/release-common.yml
--- a/.github/workflows/release-common.yml
+++ b/.github/workflows/release-common.yml
@@ -14,6 +14,13 @@ jobs:
     steps:
       - name: Git checkout
         uses: actions/checkout@v2
+      - name: Version check
+        run: |
+          common_snapshot=`grep -c "SNAPSHOT" ./common/src/main/resources/application.conf
+          if [ "$common_snapshot" -ne "0" ]; then
+            echo "dxCommon version contains '-SNAPSHOT'; releases cannot have snapshot versions"
+            exit 1
+          fi
       - name: Install java
         uses: actions/setup-java@v1
         with:
